name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test parameters and objectives
      id: test-parameters-and-objectives
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test parameters and objectives
        setup-command: sudo -H pip3 install -r requirements.txt
        command: pytest bayesian_optimization_test.py::test_parameters_and_objectives
        timeout: 10
        max-score: 5
    - name: Test function calls
      id: test-function-calls
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test function calls
        setup-command: ''
        command: pytest bayesian_optimization_test.py::test_calls
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-PARAMETERS-AND-OBJECTIVES_RESULTS: "${{steps.test-parameters-and-objectives.outputs.result}}"
        TEST-FUNCTION-CALLS_RESULTS: "${{steps.test-function-calls.outputs.result}}"
      with:
        runners: test-parameters-and-objectives,test-function-calls
